// libs/foundation/wink/core/src/components/badge/badge.tsx
import { Component, h, Host, Prop } from '@stencil/core';
import { BADGE_COLORS, BADGE_SIZES, BadgeColor, BadgeSize } from './models/badge.types';

@Component({
  tag: 'wink-badge',
  styleUrls: {
    telenet: 'styles/brands/badge.telenet.scss',
    base: 'styles/brands/badge.base.scss',
  },
  shadow: true,
})
export class Badge {
  @Prop() text = '';
  @Prop() size: BadgeSize = BADGE_SIZES.md;
  @Prop() background: BadgeColor = BADGE_COLORS.default;
  @Prop() isBold = true;

  render() {
    return <Host>{this.text}</Host>;
  }
}

// libs/foundation/demo/billing/ui/src/lib/badge/badge.component.ts
import { Component, Input } from '@angular/core';
import { WinkBadge } from '@telenet/wink-ng';

export type BadgeColor = 'dark' | 'brand' | 'default';

@Component({
  standalone: true,
  selector: 'tg-demo-badge',
  template: ` <wink-badge text="{{ content }}" is-bold size="md" [attr.background]="color"></wink-badge> `,
  styleUrls: ['./badge.component.scss'],
  imports: [WinkBadge],
})
export class BadgeComponent {
  @Input() color: BadgeColor = 'default';
  @Input() content = '';
}
